# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import protosvg_pb2 as protosvg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\x12\x07service\x1a\x0eprotosvg.proto\"1\n\x0e\x43onvertRequest\x12\x1f\n\x03svg\x18\x01 \x01(\x0b\x32\x12.protosvg.ProtoSVG\"\x1f\n\x0c\x43onvertReply\x12\x0f\n\x07svg_xml\x18\x01 \x01(\t\"0\n\rRenderRequest\x12\x1f\n\x03svg\x18\x01 \x01(\x0b\x32\x12.protosvg.ProtoSVG\"0\n\x0bRenderReply\x12\x0f\n\x07svg_xml\x18\x01 \x01(\t\x12\x10\n\x08png_data\x18\x02 \x01(\x0c\x32y\n\x04PSVG\x12\x39\n\x07\x43onvert\x12\x17.service.ConvertRequest\x1a\x15.service.ConvertReply\x12\x36\n\x06Render\x12\x16.service.RenderRequest\x1a\x14.service.RenderReplyb\x06proto3'
  ,
  dependencies=[protosvg__pb2.DESCRIPTOR,])




_CONVERTREQUEST = _descriptor.Descriptor(
  name='ConvertRequest',
  full_name='service.ConvertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='svg', full_name='service.ConvertRequest.svg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=91,
)


_CONVERTREPLY = _descriptor.Descriptor(
  name='ConvertReply',
  full_name='service.ConvertReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='svg_xml', full_name='service.ConvertReply.svg_xml', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=124,
)


_RENDERREQUEST = _descriptor.Descriptor(
  name='RenderRequest',
  full_name='service.RenderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='svg', full_name='service.RenderRequest.svg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=174,
)


_RENDERREPLY = _descriptor.Descriptor(
  name='RenderReply',
  full_name='service.RenderReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='svg_xml', full_name='service.RenderReply.svg_xml', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='png_data', full_name='service.RenderReply.png_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=224,
)

_CONVERTREQUEST.fields_by_name['svg'].message_type = protosvg__pb2._PROTOSVG
_RENDERREQUEST.fields_by_name['svg'].message_type = protosvg__pb2._PROTOSVG
DESCRIPTOR.message_types_by_name['ConvertRequest'] = _CONVERTREQUEST
DESCRIPTOR.message_types_by_name['ConvertReply'] = _CONVERTREPLY
DESCRIPTOR.message_types_by_name['RenderRequest'] = _RENDERREQUEST
DESCRIPTOR.message_types_by_name['RenderReply'] = _RENDERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConvertRequest = _reflection.GeneratedProtocolMessageType('ConvertRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:service.ConvertRequest)
  })
_sym_db.RegisterMessage(ConvertRequest)

ConvertReply = _reflection.GeneratedProtocolMessageType('ConvertReply', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:service.ConvertReply)
  })
_sym_db.RegisterMessage(ConvertReply)

RenderRequest = _reflection.GeneratedProtocolMessageType('RenderRequest', (_message.Message,), {
  'DESCRIPTOR' : _RENDERREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:service.RenderRequest)
  })
_sym_db.RegisterMessage(RenderRequest)

RenderReply = _reflection.GeneratedProtocolMessageType('RenderReply', (_message.Message,), {
  'DESCRIPTOR' : _RENDERREPLY,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:service.RenderReply)
  })
_sym_db.RegisterMessage(RenderReply)



_PSVG = _descriptor.ServiceDescriptor(
  name='PSVG',
  full_name='service.PSVG',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=226,
  serialized_end=347,
  methods=[
  _descriptor.MethodDescriptor(
    name='Convert',
    full_name='service.PSVG.Convert',
    index=0,
    containing_service=None,
    input_type=_CONVERTREQUEST,
    output_type=_CONVERTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Render',
    full_name='service.PSVG.Render',
    index=1,
    containing_service=None,
    input_type=_RENDERREQUEST,
    output_type=_RENDERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PSVG)

DESCRIPTOR.services_by_name['PSVG'] = _PSVG

# @@protoc_insertion_point(module_scope)
