app:
  port: 5001
  host: "0.0.0.0"
  thread_pool: 5
  log_level: "INFO"
service:
  font_dir: "./covergan/fonts"
  gan_weights_ilya: "./covergan/weights/covergan_ilya.pt"
  captioner_weights: "./covergan/weights/captioner.pt"
  gan_weights_2: "./covergan/weights/checkpoint_6figs_5depth_512noise.pt"
  colorer_12_weights: "./covergan/weights/colorer_12_colors-1800.pt"
