# Open fonts available from https://fonts.google.com
FONTS = [
    "Allerta Stencil",
    "Balsamiq Sans",
    "Cabin",
    "Caveat",
    "Comfortaa",
    "Fira Sans",
    "Lobster",
    "Montserrat",
    "Neucha",
    "Nunito",
    "Open Sans",
    "Oxanium",
    "Playfair Display",
    "Press Start 2P",
    "PT Serif",
    "Reggae One",
    "Roboto",
    "Schoolbell",
    "Special Elite",
    "Titillium Web",
    "Zilla Slab",
]